//Next Head
import Head from "next/head";
//Component
import Card from "../components/Card";
//Data
import data from "../data/Pricing_data.json";

export default function Home() {
  return (
    <div className="lg:h-[100vh] flex flex-col justify-center items-center space-y-10 md:p-[2rem] p-[10px]">
      <Head>
        <title>Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <h1 className="font-bold text-[3rem] text-blue-700">
          Flexible <span className="text-black">Plans</span>
        </h1>
        <h3 className="font-semibold text-gray-500">Choose a plan which works best for you</h3>
      </div>

      {/* Mapping through data and send data to component */}
      <div className="flex lg:flex-row flex-col lg:space-x-7 lg:space-y-0 space-y-3">
        {data.map((item) => {
          return <Card key={item.Plan} {...item} />;
        })}
      </div>
    </div>
  );
}
